
version: '3.4'

services:
  php-container: 
    # image: php:8.3-apache
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'no'

    volumes:
      - ./website:/var/www/html

    ports:
      - 8088:80


  mariadb-container:
    image: mariadb
    restart: 'no'
    environment:
      MARIADB_DATABASE: booking
      MARIADB_USER: booking
      MARIADB_PASSWORD: booking
      MARIADB_ROOT_PASSWORD: booking
    
    ports:
      - 13306:3306
  
    volumes:
      - ./data:/var/lib/mysql